# Site settings
title: Baptiste Delattre
general_email: delattre.baptiste@gmail.com

description: > # this means to ignore newlines until "baseurl:"
  I'm a physics engineer interested in data science/engineering. Mainly using python with packages like Dask, Plotly-Dash, pandas, scikit-learn, light-gbm, keras, Airflow.
  Recently interested in the RAPIDS project with the confluence of actors like Omnisci (MapD), Dask, CuPy.

baseurl: "/about_me" # the subpath of your site, e.g. /blog/

url: "https://batmobil.github.io" # the base hostname & protocol for your site

# twitter_username: jekyllrb
github_username: Batmobil
linkedin_username: Baptiste Delattre
# facebook_username: facebook_username
# feel free to add other links here; you will have to add the SVG icon in _layouts/footer.html

# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax

# Other options
permalink: blog/:year/:month/:title
