# Site settings
title: Baptiste Delattre
general_email: your_general_email@gmail.com

description: > # this means to ignore newlines until "baseurl:"
  Give a brief description of yourself, and maybe your passion/interests. It is displayed in search results.

baseurl: "/about-me" # the subpath of your site, e.g. /blog/

url: "https://batmobil.github.io" # the base hostname & protocol for your site

# twitter_username: jekyllrb
github_username: Batmobil
linkedin_username: Baptiste Delattre
# facebook_username: facebook_username
# feel free to add other links here; you will have to add the SVG icon in _layouts/footer.html

# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax

# Other options
permalink: blog/:year/:month/:title
